-- Deleting a quiz used to fail with a foreign key violation (surfaced as a 500
-- "Unexpected error") as soon as the quiz had ever been hosted, because
-- quiz_session.quiz_id was the only child FK in the schema without ON DELETE CASCADE.
--
-- Deleting a quiz now removes its sessions too, and through the cascades already in
-- place their participants, answers and selected options. QuizService refuses the
-- delete while a LOBBY/ACTIVE session exists, so a live lecture cannot be wiped.

-- V3 created the constraint inline, so its name was generated by Postgres. Look it up
-- instead of assuming, otherwise a differently named constraint would be left in place
-- and this migration would silently add a second, non-cascading FK.
do $$
declare
    fk_name text;
begin
    select conname into fk_name
    from pg_constraint
    where conrelid = 'quiz_session'::regclass
      and contype = 'f'
      and confrelid = 'quiz'::regclass;

    if fk_name is null then
        raise exception 'No foreign key found from quiz_session to quiz';
    end if;

    execute format('alter table quiz_session drop constraint %I', fk_name);
end $$;

alter table quiz_session
    add constraint quiz_session_quiz_id_fkey
        foreign key (quiz_id) references quiz (id) on delete cascade;
